branches:
  only:
    - master

script-anchors:
  - &script-publish
    - cd $TRAVIS_BUILD_DIR
    - yarn global add gitbook-cli
    - make pdf
    - make html

matrix:
  include:
    - os: linux
      language: node_js
      node_js: "10"
      addons:
        apt:
          packages:
            - calibre
            - calibre-bin
            - libxss1
      script: *script-publish
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          name: Build $(date +'%d.%m.%Y %R')
          file: $TRAVIS_BUILD_DIR/dist/tobanteAudio-JUCE-Cookbook.pdf
          skip_cleanup: true
          on:
            branch: master
        - provider: pages
          skip_cleanup: true
          local_dir: $TRAVIS_BUILD_DIR/dist/html
          github_token: $GITHUB_TOKEN
          keep_history: true
          on:
            branch: master
