branches:
  only:
    - master

script-anchors:
  - &script-pdf
    - cd $TRAVIS_BUILD_DIR
    - npm install mdpdf
    - make

matrix:
  include:
    - os: linux
      language: node_js
      script: *script-pdf
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: $TRAVIS_BUILD_DIR/dist/tobanteAudio-JUCE-Cookbook.pdf
        skip_cleanup: true
        on:
          all_branches: true